### ISSUE TITLE
GoLang Implementation https://github.com/mdcfrancis/gomnist1d

### ISSUE THREAD

**Issue by mdcfrancis** [greydanus/mnist1d#13]
I successfully replicated the generation of the dataset in Go, including matching the random numbers and seeds as supported in Python. Hopefully, this is useful to others as an additional way to generate a sample dataset and provide a second reference. 

https://github.com/mdcfrancis/gomnist1d

As much as possible, I followed the original code flow so that one may compare the implementations.

**Comment by greydanus** [comment]
This is great, thanks for sharing! I've linked to your repository in the "Community use cases" section of the README. Best, Sam

**Comment by mdcfrancis** [comment]
You are welcome. Thanks
