### ISSUE TITLE
Hugging Face Dataset

### ISSUE THREAD

**Issue by cakiki** [greydanus/mnist1d#18]
I've uploaded the dataset to Hugging Face: https://huggingface.co/datasets/christopher/mnist1d

Before sending a PR here linking to it, I wanted to ask:

- whether you'd prefer hosting it under your own namespace or under that of an organization.
- whether you'd like me to include the entire README from GitHub on HF.

**Comment by greydanus** [comment]
Very nice, thanks @cakiki.
* I don't need to host it under my namespace. Post the link here, when you have it, and I'll add a link to it (+credit to you) in the README.
* Include as much of the README as you feel is relevant

**Comment by cakiki** [comment]
Done with the upload and README if you'd like to take a look: https://huggingface.co/datasets/christopher/mnist1d

**Comment by greydanus** [comment]
Thanks Chris, I've linked it and given you credit in the README
