### ISSUE TITLE
Packaging this dataset

### ISSUE THREAD

**Issue by psteinb** [greydanus/mnist1d#8]
Hi, thanks for contributing this dataset as open source. Motivated by "Understanding Deep Learning", I'd love to start playing with it. 

I saw that the repo is not ready for packaging. As the code is rather straight forward, I was wondering if any PRs would be appreciated to package this as a python module. 

This would also make it more easier to use more broadly than by using the requests package. People could just go: `pip install mnist1d` and have the code for augmenting and changing under their fingers. Just a thought!

Right now, I get the following:
``` shell
python -m pip install git+https://github.com/greydanus/mnist1d.git@master
```
``` output
Collecting git+https://github.com/greydanus/mnist1d.git@master
  Cloning https://github.com/greydanus/mnist1d.git (to revision master) to /tmp/pip-req-build-eg1a_6cu
  Running command git clone --filter=blob:none --quiet https://github.com/greydanus/mnist1d.git /tmp/pip-req-build-eg1a_6cu
  Resolved https://github.com/greydanus/mnist1d.git to commit 39dd6c03785eefe60f349af94e61f864fc449644
ERROR: git+https://github.com/greydanus/mnist1d.git@master does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by greydanus** [comment]
Peter, this is a great suggestion. I haven never packaged a library before - can you help me set this up? I'm all ears.
